import type { Poi } from "./types";

export const mockPois: Poi[] = [
  {
    id: "tree-cafe",
    name: "Tree Cafe",
    category: "cafe",
    x: 43,
    y: 31,
    lat: 39.9087,
    lng: 116.3975,
    distanceMeters: 680,
    rating: 4.7,
    pricePerPerson: 48,
    sceneTags: ["安静", "插座", "适合办公", "非网红", "座位舒适"],
    reviewPositive: ["环境安静", "插座很多", "适合长坐", "店员不催"],
    reviewNegative: ["午后靠窗位偶尔满座"],
    riskTags: ["热门时段座位紧张"],
    openNow: true,
    crowdLevel: "low",
    queueMinutes: 4,
    reservationAvailable: true,
    dealAvailable: true,
    routeEtaMinutes: 10,
    nearMetro: true,
  },
  {
    id: "a-coffee",
    name: "A Coffee",
    category: "cafe",
    x: 61,
    y: 38,
    lat: 39.912,
    lng: 116.405,
    distanceMeters: 520,
    rating: 4.8,
    pricePerPerson: 62,
    sceneTags: ["很出片", "甜品", "人气高", "拍照"],
    reviewPositive: ["装修好看", "拿铁稳定", "适合拍照"],
    reviewNegative: ["音乐偏大", "排队久", "座位翻台快"],
    riskTags: ["太吵", "网红店", "排队长"],
    openNow: true,
    crowdLevel: "high",
    queueMinutes: 28,
    reservationAvailable: false,
    dealAvailable: true,
    routeEtaMinutes: 8,
    nearMetro: true,
  },
  {
    id: "bloom-cafe",
    name: "Bloom Cafe",
    category: "cafe",
    x: 35,
    y: 57,
    lat: 39.9045,
    lng: 116.391,
    distanceMeters: 860,
    rating: 4.5,
    pricePerPerson: 58,
    sceneTags: ["甜品好看", "轻食", "聊天", "拍照"],
    reviewPositive: ["甜品稳定", "下午光线好"],
    reviewNegative: ["小桌较多", "插座少", "周末略吵"],
    riskTags: ["插座少", "可能太吵"],
    openNow: true,
    crowdLevel: "medium",
    queueMinutes: 12,
    reservationAvailable: false,
    dealAvailable: true,
    routeEtaMinutes: 13,
    nearMetro: false,
  },
  {
    id: "quiet-lab",
    name: "Quiet Lab Coffee",
    category: "cafe",
    x: 52,
    y: 24,
    lat: 39.914,
    lng: 116.394,
    distanceMeters: 930,
    rating: 4.6,
    pricePerPerson: 55,
    sceneTags: ["安静", "插座", "独立座", "适合办公"],
    reviewPositive: ["二楼很安静", "单人位多", "Wi-Fi 稳定"],
    reviewNegative: ["餐食选择少"],
    riskTags: ["餐食少"],
    openNow: true,
    crowdLevel: "low",
    queueMinutes: 6,
    reservationAvailable: true,
    dealAvailable: false,
    routeEtaMinutes: 14,
    nearMetro: false,
  },
  {
    id: "green-bowl",
    name: "Green Bowl",
    category: "restaurant",
    x: 67,
    y: 63,
    lat: 39.9055,
    lng: 116.409,
    distanceMeters: 1040,
    rating: 4.6,
    pricePerPerson: 86,
    sceneTags: ["清淡", "不辣", "沙拉", "双人位", "地铁近"],
    reviewPositive: ["口味清爽", "可提前订位", "地铁口步行三分钟"],
    reviewNegative: ["高峰期上菜稍慢"],
    riskTags: ["晚高峰稍慢"],
    openNow: true,
    crowdLevel: "medium",
    queueMinutes: 8,
    reservationAvailable: true,
    dealAvailable: true,
    routeEtaMinutes: 15,
    nearMetro: true,
  },
  {
    id: "mild-pot",
    name: "Mild Pot 粥底火锅",
    category: "restaurant",
    x: 25,
    y: 45,
    lat: 39.899,
    lng: 116.3945,
    distanceMeters: 1250,
    rating: 4.4,
    pricePerPerson: 108,
    sceneTags: ["清淡", "可订位", "聚餐"],
    reviewPositive: ["粥底温和", "服务好"],
    reviewNegative: ["套餐略超预算", "店面离地铁稍远"],
    riskTags: ["超预算", "距离较远"],
    openNow: true,
    crowdLevel: "medium",
    queueMinutes: 18,
    reservationAvailable: true,
    dealAvailable: false,
    routeEtaMinutes: 19,
    nearMetro: false,
  },
  {
    id: "spicy-town",
    name: "Spicy Town",
    category: "restaurant",
    x: 73,
    y: 42,
    lat: 39.9105,
    lng: 116.4125,
    distanceMeters: 760,
    rating: 4.7,
    pricePerPerson: 92,
    sceneTags: ["川菜", "重口", "朋友聚餐"],
    reviewPositive: ["出餐快", "味道足"],
    reviewNegative: ["整体偏辣", "晚餐排队"],
    riskTags: ["吃辣", "排队长"],
    openNow: true,
    crowdLevel: "high",
    queueMinutes: 35,
    reservationAvailable: false,
    dealAvailable: true,
    routeEtaMinutes: 11,
    nearMetro: true,
  },
  {
    id: "metro-mall",
    name: "Metro Mall",
    category: "mall",
    x: 55,
    y: 70,
    lat: 39.917,
    lng: 116.404,
    distanceMeters: 600,
    rating: 4.3,
    pricePerPerson: 0,
    sceneTags: ["地铁口", "接朋友", "室内", "餐饮多"],
    reviewPositive: ["动线清楚", "地铁连通", "等人方便"],
    reviewNegative: ["晚高峰人流多"],
    riskTags: ["人流多"],
    openNow: true,
    crowdLevel: "medium",
    queueMinutes: 0,
    reservationAvailable: false,
    dealAvailable: false,
    routeEtaMinutes: 7,
    nearMetro: true,
  },
  {
    id: "book-nook",
    name: "Book Nook 书店",
    category: "activity",
    x: 40,
    y: 74,
    lat: 39.902,
    lng: 116.401,
    distanceMeters: 980,
    rating: 4.5,
    pricePerPerson: 35,
    sceneTags: ["安静", "等人", "轻活动"],
    reviewPositive: ["适合短暂停留", "环境舒服"],
    reviewNegative: ["不能长时间占座办公"],
    riskTags: ["不适合办公"],
    openNow: true,
    crowdLevel: "low",
    queueMinutes: 0,
    reservationAvailable: false,
    dealAvailable: false,
    routeEtaMinutes: 14,
    nearMetro: true,
  },
  {
    id: "closed-rooftop",
    name: "Rooftop Garden",
    category: "activity",
    x: 22,
    y: 28,
    lat: 39.8965,
    lng: 116.3875,
    distanceMeters: 1420,
    rating: 4.2,
    pricePerPerson: 30,
    sceneTags: ["拍照", "散步", "户外"],
    reviewPositive: ["视野好"],
    reviewNegative: ["下午闭园维护"],
    riskTags: ["不可用", "户外受天气影响"],
    openNow: false,
    crowdLevel: "low",
    queueMinutes: 0,
    reservationAvailable: false,
    dealAvailable: false,
    routeEtaMinutes: 21,
    nearMetro: false,
  },
  {
    id: "plain-table",
    name: "Plain Table",
    category: "restaurant",
    x: 46,
    y: 66,
    lat: 39.9132,
    lng: 116.389,
    distanceMeters: 820,
    rating: 4.5,
    pricePerPerson: 78,
    sceneTags: ["清淡", "不辣", "简餐", "安静"],
    reviewPositive: ["菜品清爽", "双人桌充足", "预算友好"],
    reviewNegative: ["门面不显眼"],
    riskTags: ["位置较隐蔽"],
    openNow: true,
    crowdLevel: "low",
    queueMinutes: 5,
    reservationAvailable: true,
    dealAvailable: true,
    routeEtaMinutes: 12,
    nearMetro: false,
  },
  {
    id: "workhub-cafe",
    name: "WorkHub Cafe",
    category: "cafe",
    x: 70,
    y: 25,
    lat: 39.9188,
    lng: 116.392,
    distanceMeters: 1180,
    rating: 4.4,
    pricePerPerson: 42,
    sceneTags: ["插座", "适合办公", "长桌", "非网红"],
    reviewPositive: ["工作位多", "咖啡套餐便宜"],
    reviewNegative: ["离地铁要多走一段", "空调偏冷"],
    riskTags: ["距离较远"],
    openNow: true,
    crowdLevel: "medium",
    queueMinutes: 9,
    reservationAvailable: true,
    dealAvailable: true,
    routeEtaMinutes: 18,
    nearMetro: false,
  },
  {
    id: "gather-tea",
    name: "Gather Tea 集合茶饮",
    category: "cafe",
    x: 58,
    y: 48,
    lat: 39.9075,
    lng: 116.402,
    distanceMeters: 420,
    rating: 4.6,
    pricePerPerson: 38,
    sceneTags: ["聊天", "朋友集合", "茶饮", "地铁近", "大桌"],
    reviewPositive: ["适合朋友先到集合", "茶饮出杯快", "座位适合聊天"],
    reviewNegative: ["周末下午略吵"],
    riskTags: ["周末略吵"],
    openNow: true,
    crowdLevel: "medium",
    queueMinutes: 7,
    reservationAvailable: false,
    dealAvailable: true,
    routeEtaMinutes: 6,
    nearMetro: true,
  },
  {
    id: "night-bites",
    name: "Night Bites 饭后小坐",
    category: "cafe",
    x: 64,
    y: 55,
    lat: 39.9068,
    lng: 116.408,
    distanceMeters: 540,
    rating: 4.5,
    pricePerPerson: 52,
    sceneTags: ["续摊", "聊天", "轻食", "夜宵"],
    reviewPositive: ["饭后续摊方便", "营业到较晚", "小食适合分享"],
    reviewNegative: ["高峰需等位"],
    riskTags: ["高峰等位"],
    openNow: true,
    crowdLevel: "medium",
    queueMinutes: 10,
    reservationAvailable: false,
    dealAvailable: true,
    routeEtaMinutes: 9,
    nearMetro: true,
  },
  {
    id: "kid-zone",
    name: "Kid Zone 奇趣亲子馆",
    category: "activity",
    x: 48,
    y: 52,
    lat: 39.9038,
    lng: 116.399,
    distanceMeters: 710,
    rating: 4.4,
    pricePerPerson: 68,
    sceneTags: ["亲子", "室内", "活动", "等待短"],
    reviewPositive: ["室内活动丰富", "适合带娃放电", "入场流程清楚"],
    reviewNegative: ["周末票需提前预约"],
    riskTags: ["周末需预约"],
    openNow: true,
    crowdLevel: "medium",
    queueMinutes: 5,
    reservationAvailable: true,
    dealAvailable: true,
    routeEtaMinutes: 11,
    nearMetro: true,
  },
  {
    id: "family-kitchen",
    name: "Family Kitchen 亲子小厨",
    category: "restaurant",
    x: 38,
    y: 62,
    lat: 39.9015,
    lng: 116.396,
    distanceMeters: 890,
    rating: 4.5,
    pricePerPerson: 72,
    sceneTags: ["亲子友好", "清淡", "不辣", "儿童椅", "可订位"],
    reviewPositive: ["有儿童餐", "上菜稳定", "环境不吵"],
    reviewNegative: ["包间需提前订"],
    riskTags: ["包间紧张"],
    openNow: true,
    crowdLevel: "low",
    queueMinutes: 6,
    reservationAvailable: true,
    dealAvailable: true,
    routeEtaMinutes: 13,
    nearMetro: false,
  },
  {
    id: "art-walk",
    name: "Art Walk 轻展漫步",
    category: "activity",
    x: 33,
    y: 40,
    lat: 39.911,
    lng: 116.388,
    distanceMeters: 950,
    rating: 4.6,
    pricePerPerson: 40,
    sceneTags: ["展览", "散步", "约会", "氛围"],
    reviewPositive: ["小型展览更新快", "适合饭后散步", "拍照光线好"],
    reviewNegative: ["部分展区较窄"],
    riskTags: ["人流偶发"],
    openNow: true,
    crowdLevel: "low",
    queueMinutes: 2,
    reservationAvailable: false,
    dealAvailable: false,
    routeEtaMinutes: 15,
    nearMetro: false,
  },
  {
    id: "mood-dine",
    name: "Mood Dine 暖光小馆",
    category: "restaurant",
    x: 42,
    y: 35,
    lat: 39.9095,
    lng: 116.393,
    distanceMeters: 640,
    rating: 4.7,
    pricePerPerson: 118,
    sceneTags: ["氛围", "约会", "双人位", "可订位"],
    reviewPositive: ["灯光柔和适合约会", "服务节奏不紧", "可提前订位"],
    reviewNegative: ["价格略高", "热门时段需等位"],
    riskTags: ["热门时段等位"],
    openNow: true,
    crowdLevel: "medium",
    queueMinutes: 14,
    reservationAvailable: true,
    dealAvailable: true,
    routeEtaMinutes: 10,
    nearMetro: true,
  },
  {
    id: "sweet-stop",
    name: "Sweet Stop 甜品驿站",
    category: "cafe",
    x: 50,
    y: 42,
    lat: 39.908,
    lng: 116.4,
    distanceMeters: 480,
    rating: 4.6,
    pricePerPerson: 45,
    sceneTags: ["甜品", "约会", "拍照", "聊天"],
    reviewPositive: ["甜品稳定", "适合饭后停留", "环境舒适"],
    reviewNegative: ["座位偏少"],
    riskTags: ["座位偏少"],
    openNow: true,
    crowdLevel: "medium",
    queueMinutes: 8,
    reservationAvailable: false,
    dealAvailable: true,
    routeEtaMinutes: 8,
    nearMetro: true,
  },
  {
    id: "campus-south",
    name: "Campus South 学校南门",
    category: "activity",
    x: 28,
    y: 58,
    lat: 39.9005,
    lng: 116.392,
    distanceMeters: 1100,
    rating: 4.2,
    pricePerPerson: 0,
    sceneTags: ["接人", "办事", "途经", "顺路"],
    reviewPositive: ["接人动线清楚", "周边餐饮多", "地铁换乘方便"],
    reviewNegative: ["放学时段人流大"],
    riskTags: ["高峰人流"],
    openNow: true,
    crowdLevel: "high",
    queueMinutes: 0,
    reservationAvailable: false,
    dealAvailable: false,
    routeEtaMinutes: 16,
    nearMetro: true,
  },
  {
    id: "quick-stop",
    name: "Quick Stop 顺路停留角",
    category: "mall",
    x: 62,
    y: 68,
    lat: 39.9155,
    lng: 116.406,
    distanceMeters: 550,
    rating: 4.3,
    pricePerPerson: 0,
    sceneTags: ["顺路", "停留", "室内", "餐饮多"],
    reviewPositive: ["办事途经方便", "室内等人", "餐饮选择多"],
    reviewNegative: ["周末人流较多"],
    riskTags: ["周末人流"],
    openNow: true,
    crowdLevel: "medium",
    queueMinutes: 0,
    reservationAvailable: false,
    dealAvailable: false,
    routeEtaMinutes: 7,
    nearMetro: true,
  },
  {
    id: "easy-pick",
    name: "Easy Pick 附近轻松点",
    category: "activity",
    x: 56,
    y: 33,
    lat: 39.9135,
    lng: 116.401,
    distanceMeters: 380,
    rating: 4.4,
    pricePerPerson: 25,
    sceneTags: ["灵活", "不赶时间", "轻活动", "附近"],
    reviewPositive: ["随到随走", "不用强计划", "附近好替换"],
    reviewNegative: ["内容较简单"],
    riskTags: ["体验较简单"],
    openNow: true,
    crowdLevel: "low",
    queueMinutes: 0,
    reservationAvailable: false,
    dealAvailable: false,
    routeEtaMinutes: 5,
    nearMetro: true,
  },
];
