import type { Poi } from "./types";

export const mockPois: Poi[] = [
  {
    id: "tree-cafe",
    name: "Tree Cafe",
    category: "cafe",
    x: 43,
    y: 31,
    lat: 39.9087,
    lng: 116.3975,
    distanceMeters: 680,
    rating: 4.7,
    pricePerPerson: 48,
    sceneTags: ["安静", "插座", "适合办公", "非网红", "座位舒适"],
    reviewPositive: ["环境安静", "插座很多", "适合长坐", "店员不催"],
    reviewNegative: ["午后靠窗位偶尔满座"],
    riskTags: ["热门时段座位紧张"],
    openNow: true,
    crowdLevel: "low",
    queueMinutes: 4,
    reservationAvailable: true,
    dealAvailable: true,
    routeEtaMinutes: 10,
    nearMetro: true,
  },
  {
    id: "a-coffee",
    name: "A Coffee",
    category: "cafe",
    x: 61,
    y: 38,
    lat: 39.912,
    lng: 116.405,
    distanceMeters: 520,
    rating: 4.8,
    pricePerPerson: 62,
    sceneTags: ["很出片", "甜品", "人气高", "拍照"],
    reviewPositive: ["装修好看", "拿铁稳定", "适合拍照"],
    reviewNegative: ["音乐偏大", "排队久", "座位翻台快"],
    riskTags: ["太吵", "网红店", "排队长"],
    openNow: true,
    crowdLevel: "high",
    queueMinutes: 28,
    reservationAvailable: false,
    dealAvailable: true,
    routeEtaMinutes: 8,
    nearMetro: true,
  },
  {
    id: "bloom-cafe",
    name: "Bloom Cafe",
    category: "cafe",
    x: 35,
    y: 57,
    lat: 39.9045,
    lng: 116.391,
    distanceMeters: 860,
    rating: 4.5,
    pricePerPerson: 58,
    sceneTags: ["甜品好看", "轻食", "聊天", "拍照"],
    reviewPositive: ["甜品稳定", "下午光线好"],
    reviewNegative: ["小桌较多", "插座少", "周末略吵"],
    riskTags: ["插座少", "可能太吵"],
    openNow: true,
    crowdLevel: "medium",
    queueMinutes: 12,
    reservationAvailable: false,
    dealAvailable: true,
    routeEtaMinutes: 13,
    nearMetro: false,
  },
  {
    id: "quiet-lab",
    name: "Quiet Lab Coffee",
    category: "cafe",
    x: 52,
    y: 24,
    lat: 39.914,
    lng: 116.394,
    distanceMeters: 930,
    rating: 4.6,
    pricePerPerson: 55,
    sceneTags: ["安静", "插座", "独立座", "适合办公"],
    reviewPositive: ["二楼很安静", "单人位多", "Wi-Fi 稳定"],
    reviewNegative: ["餐食选择少"],
    riskTags: ["餐食少"],
    openNow: true,
    crowdLevel: "low",
    queueMinutes: 6,
    reservationAvailable: true,
    dealAvailable: false,
    routeEtaMinutes: 14,
    nearMetro: false,
  },
  {
    id: "green-bowl",
    name: "Green Bowl",
    category: "restaurant",
    x: 67,
    y: 63,
    lat: 39.9055,
    lng: 116.409,
    distanceMeters: 1040,
    rating: 4.6,
    pricePerPerson: 86,
    sceneTags: ["清淡", "不辣", "沙拉", "双人位", "地铁近"],
    reviewPositive: ["口味清爽", "可提前订位", "地铁口步行三分钟"],
    reviewNegative: ["高峰期上菜稍慢"],
    riskTags: ["晚高峰稍慢"],
    openNow: true,
    crowdLevel: "medium",
    queueMinutes: 8,
    reservationAvailable: true,
    dealAvailable: true,
    routeEtaMinutes: 15,
    nearMetro: true,
  },
  {
    id: "mild-pot",
    name: "Mild Pot 粥底火锅",
    category: "restaurant",
    x: 25,
    y: 45,
    lat: 39.899,
    lng: 116.3945,
    distanceMeters: 1250,
    rating: 4.4,
    pricePerPerson: 108,
    sceneTags: ["清淡", "可订位", "聚餐"],
    reviewPositive: ["粥底温和", "服务好"],
    reviewNegative: ["套餐略超预算", "店面离地铁稍远"],
    riskTags: ["超预算", "距离较远"],
    openNow: true,
    crowdLevel: "medium",
    queueMinutes: 18,
    reservationAvailable: true,
    dealAvailable: false,
    routeEtaMinutes: 19,
    nearMetro: false,
  },
  {
    id: "spicy-town",
    name: "Spicy Town",
    category: "restaurant",
    x: 73,
    y: 42,
    lat: 39.9105,
    lng: 116.4125,
    distanceMeters: 760,
    rating: 4.7,
    pricePerPerson: 92,
    sceneTags: ["川菜", "重口", "朋友聚餐"],
    reviewPositive: ["出餐快", "味道足"],
    reviewNegative: ["整体偏辣", "晚餐排队"],
    riskTags: ["吃辣", "排队长"],
    openNow: true,
    crowdLevel: "high",
    queueMinutes: 35,
    reservationAvailable: false,
    dealAvailable: true,
    routeEtaMinutes: 11,
    nearMetro: true,
  },
  {
    id: "metro-mall",
    name: "Metro Mall",
    category: "mall",
    x: 55,
    y: 70,
    lat: 39.917,
    lng: 116.404,
    distanceMeters: 600,
    rating: 4.3,
    pricePerPerson: 0,
    sceneTags: ["地铁口", "接朋友", "室内", "餐饮多"],
    reviewPositive: ["动线清楚", "地铁连通", "等人方便"],
    reviewNegative: ["晚高峰人流多"],
    riskTags: ["人流多"],
    openNow: true,
    crowdLevel: "medium",
    queueMinutes: 0,
    reservationAvailable: false,
    dealAvailable: false,
    routeEtaMinutes: 7,
    nearMetro: true,
  },
  {
    id: "book-nook",
    name: "Book Nook 书店",
    category: "activity",
    x: 40,
    y: 74,
    lat: 39.902,
    lng: 116.401,
    distanceMeters: 980,
    rating: 4.5,
    pricePerPerson: 35,
    sceneTags: ["安静", "等人", "轻活动"],
    reviewPositive: ["适合短暂停留", "环境舒服"],
    reviewNegative: ["不能长时间占座办公"],
    riskTags: ["不适合办公"],
    openNow: true,
    crowdLevel: "low",
    queueMinutes: 0,
    reservationAvailable: false,
    dealAvailable: false,
    routeEtaMinutes: 14,
    nearMetro: true,
  },
  {
    id: "closed-rooftop",
    name: "Rooftop Garden",
    category: "activity",
    x: 22,
    y: 28,
    lat: 39.8965,
    lng: 116.3875,
    distanceMeters: 1420,
    rating: 4.2,
    pricePerPerson: 30,
    sceneTags: ["拍照", "散步", "户外"],
    reviewPositive: ["视野好"],
    reviewNegative: ["下午闭园维护"],
    riskTags: ["不可用", "户外受天气影响"],
    openNow: false,
    crowdLevel: "low",
    queueMinutes: 0,
    reservationAvailable: false,
    dealAvailable: false,
    routeEtaMinutes: 21,
    nearMetro: false,
  },
  {
    id: "plain-table",
    name: "Plain Table",
    category: "restaurant",
    x: 46,
    y: 66,
    lat: 39.9132,
    lng: 116.389,
    distanceMeters: 820,
    rating: 4.5,
    pricePerPerson: 78,
    sceneTags: ["清淡", "不辣", "简餐", "安静"],
    reviewPositive: ["菜品清爽", "双人桌充足", "预算友好"],
    reviewNegative: ["门面不显眼"],
    riskTags: ["位置较隐蔽"],
    openNow: true,
    crowdLevel: "low",
    queueMinutes: 5,
    reservationAvailable: true,
    dealAvailable: true,
    routeEtaMinutes: 12,
    nearMetro: false,
  },
  {
    id: "workhub-cafe",
    name: "WorkHub Cafe",
    category: "cafe",
    x: 70,
    y: 25,
    lat: 39.9188,
    lng: 116.392,
    distanceMeters: 1180,
    rating: 4.4,
    pricePerPerson: 42,
    sceneTags: ["插座", "适合办公", "长桌", "非网红"],
    reviewPositive: ["工作位多", "咖啡套餐便宜"],
    reviewNegative: ["离地铁要多走一段", "空调偏冷"],
    riskTags: ["距离较远"],
    openNow: true,
    crowdLevel: "medium",
    queueMinutes: 9,
    reservationAvailable: true,
    dealAvailable: true,
    routeEtaMinutes: 18,
    nearMetro: false,
  },
];
